image:
- Visual Studio 2017
- Ubuntu

version: 0.1.0.{build}

# Only clone the current branch and no history
clone_depth: 1

pull_requests:
  # Do not increment build number for pull requests
  do_not_increment_build_number: true

nuget:
  # Do not publish NuGet packages for pull requests
  disable_publish_on_pr: true

environment:
  # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOCKER_PASS:
    secure: 7xusxxMFy9iURl0Ktuzri5XyT3/NDKlsU3kkfJ+Sq90=

skip_commits:
  files:
    - README.md

init:
  - git config --global core.autocrlf false

configuration:
  - Release

for:
  -
    matrix:
      only:
        - image: Visual Studio 2017
    before_build:
      - dotnet restore DotNetRu.Server.sln
    after_test:
      - dotnet publish ./src/ServiceHost/ServiceHost.csproj --configuration Release --no-restore --output ./../../artifacts /p:SolutionDir=%APPVEYOR_BUILD_FOLDER% /p:SolutionName=DotNetRu.Server
  -
    matrix:
      only:
        - image: Ubuntu
    before_build:
      - dotnet restore DotNetRu.Server.sln
    build_script:
      - ps: .\build\build-docker.ps1
    test_script:
      - dotnet build ./test/ServiceHost.Tests/ServiceHost.Tests.csproj --configuration Release /p:SolutionDir=$APPVEYOR_BUILD_FOLDER /p:SolutionName=DotNetRu.Server
      - dotnet test ./test/ServiceHost.Tests/ServiceHost.Tests.csproj --configuration Release --no-build
    after_test:
      - dotnet publish ./src/ServiceHost/ServiceHost.csproj --configuration Release --no-restore --output ./../../artifacts /p:SolutionDir=$APPVEYOR_BUILD_FOLDER /p:SolutionName=DotNetRu.Server
    deploy_script:
      - ps: .\build\deploy-docker.ps1

build:
  project: DotNetRu.Server.sln
  publish_nuget: false
  publish_aspnet_core: false
  publish_core_console: false
  verbosity: minimal

deploy: off